version: '3'
services:
  qsl-pdf-generator:
    build: ./
    container_name: 'qsl-pdf-generator'
    environment:
      - PYTHONPATH=./classes
    command: /bin/bash -c "cd /work && poetry update && poetry install && poetry run python app.py"
    volumes:
      - ./:/work
      - ./output:/output
