version: '3'
services:
  qsl-pdf-generator:
    build: ./
    container_name: 'qsl-pdf-generator'
    tty: true
    working_dir: /work
    command: >
      /bin/bash -c "poetry install &&
      poetry run python app.py &&
      tail -f /dev/null"
    volumes:
      - ./:/work
