name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Analysing the code with pylint
      env:
        PYTHONPATH: ./qsl_pdf_publisher
      run: |
        poetry run pylint `ls -R|grep .py$|xargs`
